apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: statics.mykubernetes.acme.org
  labels:
    app: staticsimporter
    mylabel: stuff
spec:
  group: mykubernetes.acme.org 
  scope: Namespaced
  version: v1
  names:
    kind: Static
    listKind: StaticList
    plural: statics
    singular: static
    shortNames:
      - st
