apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: statics.mykubernetes.acme.org
  labels:
    app: staticsimporter
    mylabel: stuff
spec:
  group: mykubernetes.acme.org 
  scope: Namespaced
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                repository:
                  type: string
                  default: https://repo.backbase.com
                repousername:
                  type: string
                repopassword:
                  type: string
                statics:
                  type: array
                  items:
                    type: string
                auth:
                  type: string
                  default: edge
                provisioning:
                  type: string
                  default: edge
                password:
                  type: string
                  default: admin
                username:
                  type: string
                  default: admin
  names:
    kind: Static
    listKind: StaticList
    plural: statics
    singular: static
    shortNames:
      - st


